'use client';

import { useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'openvigie.watch-plan.v1';

type WatchLine = { id: string; axis: string; question: string; keywords: string; sourceIds: string[]; frequency: string; criticality: 1 | 2 | 3 };
type Source = { id: string; name: string; family: string; url: string; feed: string; authority: number; relevance: number; freshness: number; access: number };

const SOURCES: Source[] = [
  { id: 'cert-alertes', name: 'CERT-FR · Alertes', family: 'CERT gouvernemental', url: 'https://cert.ssi.gouv.fr/alerte/', feed: 'https://cert.ssi.gouv.fr/alerte/feed/', authority: 2, relevance: 2, freshness: 2, access: 2 },
  { id: 'cert-avis', name: 'CERT-FR · Avis', family: 'CERT gouvernemental', url: 'https://cert.ssi.gouv.fr/avis/', feed: 'https://cert.ssi.gouv.fr/avis/feed/', authority: 2, relevance: 2, freshness: 2, access: 2 },
  { id: 'cisa-kev', name: 'CISA KEV', family: 'Agence gouvernementale', url: 'https://www.cisa.gov/known-exploited-vulnerabilities-catalog', feed: 'https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json', authority: 2, relevance: 2, freshness: 2, access: 2 },
  { id: 'cisa-advisories', name: 'CISA Advisories', family: 'Agence gouvernementale', url: 'https://www.cisa.gov/news-events/cybersecurity-advisories', feed: 'https://www.cisa.gov/cybersecurity-advisories/all.xml', authority: 2, relevance: 2, freshness: 2, access: 2 },
  { id: 'nvd', name: 'NVD / NIST', family: 'Base CVE officielle', url: 'https://nvd.nist.gov/', feed: 'https://services.nvd.nist.gov/rest/json/cves/2.0', authority: 2, relevance: 2, freshness: 2, access: 2 },
  { id: 'cisco', name: 'Cisco PSIRT', family: 'Éditeur', url: 'https://sec.cloudapps.cisco.com/security/center/publicationListing.x', feed: 'https://sec.cloudapps.cisco.com/security/center/psirtrss20/CiscoSecurityAdvisory.xml', authority: 2, relevance: 2, freshness: 2, access: 2 },
  { id: 'microsoft', name: 'Microsoft MSRC', family: 'Éditeur', url: 'https://msrc.microsoft.com/update-guide/', feed: 'https://api.msrc.microsoft.com/update-guide/rss', authority: 2, relevance: 2, freshness: 2, access: 2 },
  { id: 'paloalto', name: 'Palo Alto PSIRT', family: 'Éditeur', url: 'https://security.paloaltonetworks.com/', feed: 'https://security.paloaltonetworks.com/rss.xml', authority: 2, relevance: 2, freshness: 2, access: 2 },
  { id: 'openssf', name: 'OpenSSF', family: 'Fondation open source', url: 'https://openssf.org/', feed: 'https://openssf.org/feed/', authority: 2, relevance: 2, freshness: 2, access: 2 },
  { id: 'github-supply', name: 'GitHub Supply Chain', family: 'Éditeur / recherche', url: 'https://github.blog/security/supply-chain-security/', feed: 'https://github.blog/security/supply-chain-security/feed/', authority: 2, relevance: 2, freshness: 2, access: 2 },
  { id: 'citizenlab', name: 'Citizen Lab', family: 'Recherche indépendante', url: 'https://citizenlab.ca/', feed: 'https://citizenlab.ca/feed/', authority: 2, relevance: 2, freshness: 2, access: 2 },
  { id: 'amnesty', name: 'Amnesty Security Lab', family: 'Recherche forensique', url: 'https://securitylab.amnesty.org/', feed: 'https://securitylab.amnesty.org/latest/feed/', authority: 2, relevance: 2, freshness: 2, access: 2 },
  { id: 'eff', name: 'Electronic Frontier Foundation', family: 'Droits numériques', url: 'https://www.eff.org/', feed: 'https://www.eff.org/rss/updates.xml', authority: 2, relevance: 2, freshness: 2, access: 2 },
  { id: 'bleeping', name: 'BleepingComputer', family: 'Presse spécialisée', url: 'https://www.bleepingcomputer.com/', feed: 'https://www.bleepingcomputer.com/feed/', authority: 1, relevance: 2, freshness: 2, access: 2 },
  { id: 'record', name: 'The Record', family: 'Presse spécialisée', url: 'https://therecord.media/', feed: 'https://therecord.media/feed', authority: 1, relevance: 2, freshness: 2, access: 2 },
];

const DEFAULT_LINES: WatchLine[] = [
  { id: 'w1', axis: 'Vulnérabilités & correctifs', question: 'Quelles vulnérabilités critiques ou exploitées affectent les produits présents dans le parc ?', keywords: 'CVE; KEV; zero-day; RCE; exploited; vulnérabilité critique', sourceIds: ['cert-alertes', 'cisa-kev', 'nvd'], frequency: 'Temps réel', criticality: 3 },
  { id: 'w2', axis: 'Vulnérabilités & correctifs', question: 'Quels correctifs et versions remédiées sont publiés par les éditeurs du parc ?', keywords: 'security advisory; fixed version; patch; mitigation; workaround; PSIRT', sourceIds: ['cert-avis', 'cisco', 'microsoft', 'paloalto'], frequency: 'Quotidienne', criticality: 3 },
  { id: 'w3', axis: 'Vulnérabilités & correctifs', question: 'Quelles preuves d’exploitation publique modifient la priorité de traitement ?', keywords: 'proof of concept; PoC; exploit; exploitation active; weaponized', sourceIds: ['cisa-kev', 'cisa-advisories', 'bleeping'], frequency: 'Quotidienne', criticality: 3 },
  { id: 'w4', axis: 'Menaces & conflits cyber', question: 'Quelles campagnes ciblent les organisations françaises ou européennes ?', keywords: 'France; Europe; campagne; intrusion set; APT; espionnage; ransomware', sourceIds: ['cert-alertes', 'cisa-advisories', 'record'], frequency: 'Quotidienne', criticality: 2 },
  { id: 'w5', axis: 'Menaces & conflits cyber', question: 'Quels acteurs, alias et modes opératoires émergent dans les conflits géopolitiques ?', keywords: 'APT; threat actor; alias; TTP; Russia; China; Iran; North Korea; Ukraine', sourceIds: ['cisa-advisories', 'record', 'bleeping'], frequency: 'Hebdomadaire', criticality: 2 },
  { id: 'w6', axis: 'Supply chain & VPN', question: 'Quels composants open source ou dépendances sont compromis en amont ?', keywords: 'supply chain; dependency confusion; package; npm; PyPI; maintainer; backdoor', sourceIds: ['openssf', 'github-supply', 'cisa-advisories'], frequency: 'Quotidienne', criticality: 2 },
  { id: 'w7', axis: 'Supply chain & VPN', question: 'Quelles failles affectent les passerelles VPN et équipements exposés ?', keywords: 'VPN; SSL-VPN; gateway; firewall; FortiGate; Ivanti; SonicWall; Citrix; Pulse Secure', sourceIds: ['cert-alertes', 'cisa-kev', 'nvd'], frequency: 'Quotidienne', criticality: 2 },
  { id: 'w8', axis: 'Supply chain & VPN', question: 'Quelles mesures de remédiation réduisent le risque de compromission initiale ?', keywords: 'upgrade; mitigation; IOC; rotate credentials; disable; hardening', sourceIds: ['cert-avis', 'cisa-advisories', 'cisco'], frequency: 'Hebdomadaire', criticality: 1 },
  { id: 'w9', axis: 'Surveillance & vie privée', question: 'Quels nouveaux usages de logiciels espions ciblent journalistes, militants ou responsables publics ?', keywords: 'Pegasus; Predator; mercenary spyware; NSO Group; zero-click; forensic', sourceIds: ['citizenlab', 'amnesty', 'eff'], frequency: 'Hebdomadaire', criticality: 2 },
  { id: 'w10', axis: 'Surveillance & vie privée', question: 'Quelles restrictions techniques ou politiques menacent les systèmes mobiles durcis ?', keywords: 'GrapheneOS; Pixel; attestation; Android; device integrity; sideloading; restriction', sourceIds: ['eff', 'citizenlab', 'bleeping'], frequency: 'Hebdomadaire', criticality: 1 },
  { id: 'w11', axis: 'Surveillance & vie privée', question: 'Quelles évolutions réglementaires modifient le chiffrement et la protection des données ?', keywords: 'encryption; chiffrement; DMA; DSA; ePrivacy; lawful access; client-side scanning', sourceIds: ['eff', 'amnesty', 'record'], frequency: 'Mensuelle', criticality: 1 },
  { id: 'w12', axis: 'Menaces & conflits cyber', question: 'Quels incidents majeurs nécessitent une analyse de tendance mensuelle ?', keywords: 'cyberattack; disruption; critical infrastructure; data breach; influence operation', sourceIds: ['cert-alertes', 'record', 'bleeping'], frequency: 'Mensuelle', criticality: 1 },
];

const uid = () => `watch-${Date.now()}-${Math.random().toString(16).slice(2)}`;

export default function WatchPlan() {
  const [lines, setLines] = useState<WatchLine[]>(DEFAULT_LINES);
  const [view, setView] = useState<'questions' | 'sources'>('questions');
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? 'null'); if (Array.isArray(saved)) setLines(saved); } catch { /* keep defaults */ } }, []);
  useEffect(() => { localStorage.setItem(STORAGE_KEY, JSON.stringify(lines)); }, [lines]);
  const axes = new Set(lines.map((line) => line.axis)).size;
  const immediate = lines.filter((line) => line.criticality === 3).length;
  const families = new Set(SOURCES.map((source) => source.family)).size;
  const update = (id: string, patch: Partial<WatchLine>) => setLines((current) => current.map((line) => line.id === id ? { ...line, ...patch } : line));
  const toggleSource = (line: WatchLine, sourceId: string) => update(line.id, { sourceIds: line.sourceIds.includes(sourceId) ? line.sourceIds.filter((id) => id !== sourceId) : [...line.sourceIds, sourceId] });
  const exportCsv = () => {
    const quote = (value: string | number) => `"${String(value).replaceAll('"', '""')}"`;
    const rows = [['Axe', 'Question', 'Mots-clés', 'Sources', 'Fréquence', 'Criticité'], ...lines.map((line) => [line.axis, line.question, line.keywords, line.sourceIds.map((id) => SOURCES.find((source) => source.id === id)?.name ?? id).join(' | '), line.frequency, line.criticality])];
    const blob = new Blob([`\uFEFF${rows.map((row) => row.map(quote).join(';')).join('\n')}`], { type: 'text/csv;charset=utf-8' });
    const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'openvigie-plan-de-veille.csv'; link.click(); URL.revokeObjectURL(link.href);
  };
  const representedSources = useMemo(() => new Set(lines.flatMap((line) => line.sourceIds)).size, [lines]);

  return <div className="watch-plan">
    <header className="watch-plan-hero glass-panel"><div><p className="eyebrow neon">Cadrage stratégique</p><h1>Plan de veille</h1><p>Transformez vos objectifs de veille en questions surveillables, reliées à des mots-clés, des sources vérifiées et un rythme d’analyse.</p></div><div className="watch-plan-actions"><button type="button" onClick={() => setLines((current) => [...current, { id: uid(), axis: 'Nouvel axe', question: 'Nouvelle question de veille', keywords: '', sourceIds: [], frequency: 'Hebdomadaire', criticality: 1 }])}>+ Ajouter une ligne</button><button type="button" onClick={exportCsv}>Exporter CSV</button></div></header>
    <section className="watch-plan-stats"><article><span>Axes couverts</span><strong>{axes}</strong><p>Minimum demandé : 2</p></article><article><span>Questions actives</span><strong>{lines.length}</strong><p>Lignes sauvegardées sur cet appareil</p></article><article><span>Sources représentées</span><strong>{representedSources}/15</strong><p>{families} familles de sources</p></article><article data-alert={immediate > 3}><span>Alertes immédiates</span><strong>{immediate}</strong><p>Maximum recommandé : 3</p></article></section>
    <section className="watch-plan-panel glass-panel"><header><div><span>MÉTHODE DE VEILLE</span><h2>{view === 'questions' ? 'Questions et périmètre' : 'Sources qualifiées'}</h2></div><nav><button type="button" aria-pressed={view === 'questions'} onClick={() => setView('questions')}>Questions</button><button type="button" aria-pressed={view === 'sources'} onClick={() => setView('sources')}>Sources et scoring</button></nav></header>
      {view === 'questions' ? <div className="watch-lines">{lines.map((line, index) => <details key={line.id}><summary><b>{String(index + 1).padStart(2, '0')}</b><span><em>{line.axis}</em><strong>{line.question}</strong><small>{line.frequency} · Criticité {line.criticality}/3 · {line.sourceIds.length} source{line.sourceIds.length > 1 ? 's' : ''}</small></span><i data-level={line.criticality}>{line.criticality}</i></summary><div className="watch-line-editor"><label><span>Axe</span><input value={line.axis} onChange={(event) => update(line.id, { axis: event.target.value })} /></label><label className="wide"><span>Question précise et vérifiable</span><textarea value={line.question} onChange={(event) => update(line.id, { question: event.target.value })} /></label><label className="wide"><span>Mots-clés, variantes et alias</span><textarea value={line.keywords} onChange={(event) => update(line.id, { keywords: event.target.value })} /></label><label><span>Fréquence</span><select value={line.frequency} onChange={(event) => update(line.id, { frequency: event.target.value })}><option>Temps réel</option><option>Quotidienne</option><option>Hebdomadaire</option><option>Mensuelle</option></select></label><label><span>Criticité</span><select value={line.criticality} onChange={(event) => update(line.id, { criticality: Number(event.target.value) as 1 | 2 | 3 })}><option value="1">1 · Information</option><option value="2">2 · Prioritaire</option><option value="3">3 · Immédiate</option></select></label><fieldset className="wide"><legend>Sources associées</legend><div>{SOURCES.map((source) => <label key={source.id}><input type="checkbox" checked={line.sourceIds.includes(source.id)} onChange={() => toggleSource(line, source.id)} /><span>{source.name}</span></label>)}</div></fieldset><button className="watch-delete" type="button" onClick={() => setLines((current) => current.filter((item) => item.id !== line.id))}>Supprimer cette ligne</button></div></details>)}</div> : <div className="source-score-table"><table><thead><tr><th>Source et famille</th><th>Autorité</th><th>Pertinence</th><th>Fraîcheur</th><th>Accès</th><th>Total</th><th>Accès vérifié</th></tr></thead><tbody>{SOURCES.map((source) => { const total = source.authority + source.relevance + source.freshness + source.access; return <tr key={source.id}><td><strong>{source.name}</strong><span>{source.family}</span></td><td>{source.authority}/2</td><td>{source.relevance}/2</td><td>{source.freshness}/2</td><td>{source.access}/2</td><td><b data-pass={total >= 4}>{total}/8</b></td><td><a href={source.url} target="_blank" rel="noreferrer">Site ↗</a><a href={source.feed} target="_blank" rel="noreferrer">Flux/API ↗</a></td></tr>; })}</tbody></table><footer><strong>Règle de qualification</strong><span>Chaque critère est noté de 0 à 2. Une source obtenant moins de 4/8 doit être écartée. Les 15 accès ci-dessus ont répondu correctement lors du contrôle du 1er septembre 2026.</span></footer></div>}
    </section>
  </div>;
}
